[book]
title = "MarsDB 内部構造"
description = "MarsDB の内部設計"
authors = ["Kenji Noguchi"]
language = "ja"
src = "../src/internals/ja"

[build]
build-dir = "../book/ja"

[output.html]
git-repository-url = "https://github.com/knoguchi/marsdb"
site-url = "/marsdb/ja/"
additional-js = ["../mermaid.min.js", "../mermaid-init.js"]

[output.html.search]
enable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
